name: Production

on: 
  push:
    branches:
      - master

jobs:

  test_build_and_run:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1

    - name: Build the Terraform docker image
      run: |
        echo Building a Terraform Docker container with our new configuration
        docker build . --file Dockerfile --tag ignw/dc-2020-aci-terraform:latest

    - name: Apply the terraform config
      run: |
        echo Running Terraform apply against the Sandbox
        docker run ignw/dc-2020-aci-terraform:latest apply.sh